/**
 * Generates supabase/seed.sql from src/constants/sample-content.ts so the
 * demo content and the database seed never drift apart.
 *
 * Run: npm run seed:generate
 */
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'

const root = process.cwd()
const mod = await import(pathToFileURL(join(root, 'src/constants/sample-content.ts')).href)
const { sampleProjects, sampleNotes, sampleTags, sampleNowItems, sampleProfile, sampleGallery } = mod

const q = (value) => {
  if (value === null || value === undefined) return 'null'
  if (typeof value === 'number') return String(value)
  if (typeof value === 'boolean') return value ? 'true' : 'false'
  const text = String(value)
  if (text.includes('\n') || text.includes("'")) {
    if (text.includes('$md$')) throw new Error('Content contains the $md$ delimiter')
    return `$md$${text}$md$`
  }
  return `'${text}'`
}
const arr = (values) => `array[${values.map(q).join(', ')}]::text[]`

const lines = []
lines.push('-- ============================================================================')
lines.push('-- fajar.codes — sample content')
lines.push('-- GENERATED by scripts/generate-seed.mjs from src/constants/sample-content.ts.')
lines.push('-- Safe to re-run: rows are upserted by slug / natural key.')
lines.push('-- ============================================================================')
lines.push('')
lines.push('begin;')
lines.push('')

// Tags
lines.push('-- tags -----------------------------------------------------------------------')
for (const t of sampleTags) {
  lines.push(`insert into public.tags (name, slug) values (${q(t.name)}, ${q(t.slug)}) on conflict (slug) do update set name = excluded.name;`)
}
lines.push('')

// Projects
lines.push('-- projects -------------------------------------------------------------------')
for (const p of sampleProjects) {
  lines.push(`insert into public.projects (title, slug, short_description, content, category, year, role, tech_stack, cover_url, live_url, repository_url, status, featured, sort_order, created_at, updated_at)`)
  lines.push(`values (${q(p.title)}, ${q(p.slug)}, ${q(p.shortDescription)}, ${q(p.content)}, ${q(p.category)}, ${p.year}, ${q(p.role)}, ${arr(p.techStack)}, ${q(p.coverUrl)}, ${q(p.liveUrl)}, ${q(p.repositoryUrl)}, ${q(p.status)}, ${q(p.featured)}, ${p.sortOrder}, ${q(p.createdAt)}, ${q(p.updatedAt)})`)
  lines.push(`on conflict (slug) do update set title = excluded.title, short_description = excluded.short_description, content = excluded.content, category = excluded.category, year = excluded.year, role = excluded.role, tech_stack = excluded.tech_stack, cover_url = excluded.cover_url, live_url = excluded.live_url, repository_url = excluded.repository_url, status = excluded.status, featured = excluded.featured, sort_order = excluded.sort_order;`)
  lines.push('')
  if (p.images.length > 0) {
    lines.push(`delete from public.project_images where project_id = (select id from public.projects where slug = ${q(p.slug)});`)
    for (const img of p.images) {
      lines.push(`insert into public.project_images (project_id, image_url, caption, sort_order) values ((select id from public.projects where slug = ${q(p.slug)}), ${q(img.imageUrl)}, ${q(img.caption)}, ${img.sortOrder});`)
    }
    lines.push('')
  }
}

// Notes
lines.push('-- notes ----------------------------------------------------------------------')
for (const n of sampleNotes) {
  lines.push(`insert into public.notes (title, slug, excerpt, content, cover_url, reading_time, status, published_at, created_at, updated_at)`)
  lines.push(`values (${q(n.title)}, ${q(n.slug)}, ${q(n.excerpt)}, ${q(n.content)}, ${q(n.coverUrl)}, ${n.readingTime}, ${q(n.status)}, ${q(n.publishedAt)}, ${q(n.createdAt)}, ${q(n.updatedAt)})`)
  lines.push(`on conflict (slug) do update set title = excluded.title, excerpt = excluded.excerpt, content = excluded.content, cover_url = excluded.cover_url, reading_time = excluded.reading_time, status = excluded.status, published_at = excluded.published_at;`)
  lines.push(`delete from public.note_tags where note_id = (select id from public.notes where slug = ${q(n.slug)});`)
  for (const t of n.tags) {
    lines.push(`insert into public.note_tags (note_id, tag_id) values ((select id from public.notes where slug = ${q(n.slug)}), (select id from public.tags where slug = ${q(t.slug)}));`)
  }
  lines.push('')
}

// Now items (replace all)
lines.push('-- now_items ------------------------------------------------------------------')
lines.push('delete from public.now_items;')
for (const n of sampleNowItems) {
  lines.push(`insert into public.now_items (type, title, description, url, is_active, updated_at) values (${q(n.type)}, ${q(n.title)}, ${q(n.description)}, ${q(n.url)}, ${q(n.isActive)}, ${q(n.updatedAt)});`)
}
lines.push('')

// Gallery (replace all)
lines.push('-- gallery_photos ---------------------------------------------------------------')
lines.push('delete from public.gallery_photos;')
for (const g of sampleGallery) {
  lines.push(`insert into public.gallery_photos (title, caption, image_url, width, height, location, taken_at, is_published, sort_order) values (${q(g.title)}, ${q(g.caption)}, ${q(g.imageUrl)}, ${q(g.width)}, ${q(g.height)}, ${q(g.location)}, ${q(g.takenAt)}, ${q(g.isPublished)}, ${g.sortOrder});`)
}
lines.push('')

// Profile: promote the first user and fill in public details.
lines.push('-- profile --------------------------------------------------------------------')
lines.push('-- Promotes the account whose email matches :admin_email (set below) to admin and')
lines.push('-- fills in the public profile. Create the user in Authentication → Users first.')
lines.push(`update public.profiles set`)
lines.push(`  role = 'admin',`)
lines.push(`  full_name = ${q(sampleProfile.fullName)},`)
lines.push(`  username = ${q(sampleProfile.username)},`)
lines.push(`  headline = ${q(sampleProfile.headline)},`)
lines.push(`  bio = ${q(sampleProfile.bio)},`)
lines.push(`  avatar_url = ${q(sampleProfile.avatarUrl)},`)
lines.push(`  location = ${q(sampleProfile.location)},`)
lines.push(`  email = ${q(sampleProfile.email)}`)
lines.push(`where email = 'CHANGE_ME@example.com'; -- ← replace with the email you signed up with`)
lines.push('')
lines.push('commit;')

writeFileSync(join(root, 'supabase/seed.sql'), lines.join('\n') + '\n')
console.log(`Wrote supabase/seed.sql (${sampleProjects.length} projects, ${sampleNotes.length} notes, ${sampleTags.length} tags, ${sampleGallery.length} photos).`)
